server:
  port: ${peer2.server.port}
spring:
  profiles: peer2
  zipkin:
    base-url: ${spring.zipkin.base-url}
  datasource:
    url: jdbc:mysql://${spring.mysql.host}:${spring.mysql.port}/${spring.mysql.database}?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: ${spring.mysql.username}
    password: ${spring.mysql.password}
  redis:
    host: ${spring.redis.host}
    port: ${spring.redis.port}
    password: ${spring.redis.password}
    database: ${spring.redis.database}
    timeout: ${spring.redis.timeout}

eureka:
  client:
    serviceUrl:
      defaultZone: ${peer2.eureka.client.serviceUrl.defaultZone}

#TC配置信息
tx-lcn:
  client:
    manager-address: ${peer2.tx-lcn.client.manager-address}
